version: "3.8"

services:
  web:
    restart: always
    build: .
    working_dir: /code/src
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16.1
    container_name: ecommerce
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Masinga*2024
